### ISSUE TITLE
VKTS CMake error language dialect C++11

### ISSUE THREAD

**Issue by SaschaWillems** [McNopper/Vulkan#1]
Using CMake 3.1.1, configuring for MingW (on windows) works fine, but trying to configure for Visual Studio 2015 (x64) CMake will output this error :

`CMake Error in CMakeLists.txt:
  Target "VKTS" requires the language dialect "CXX11" (with compiler
  extensions), but CMake does not know the compile flags to use to enable it.
`

The solution is generated though and compiles fine, so this may not be critical.

Edit : The same error message occurs with the CMakeLists.txt for the examples.

**Comment by McNopper** [comment]
Please use the latest CMake. There are no problems. I will check for new minimum CMake version,

**Comment by McNopper** [comment]
Just tested with CMake 3.2.0. Will update the files. Thanks.
