### ISSUE TITLE
last commit

### ISSUE THREAD

**Issue by andreluizbarbieri** [McNopper/Vulkan#10]
I updated project with the last commit via git and the compilation show errors:
Error	C1083	Cannot open source file: 'VKTS\src\layer0\frustum\frustum.cpp': No such file or directory
Error	C1083	Cannot open source file: 'VKTS\src\layer0\geometry\aabb.cpp': No such file or directory
Error	C1083	Cannot open source file: 'VKTS\src\layer0\geometry\obb.cpp': No such file or directory

**Comment by McNopper** [comment]
I have refactored the project and did move some files.
I just did a successful rebuild of the project I commited.

I assume, the project/make files are outdated.

Please refresh (F5 under Eclipse) the project and/or the recreate the make files.

**Comment by andreluizbarbieri** [comment]
Ok. I did not do the Make again, just Rebuild... Thanks.

**Comment by McNopper** [comment]
No problem - happened to me many times - so I knew immediatelly :-)
