### ISSUE TITLE
Example 6 looks wrong on Skylake/Mesa

### ISSUE THREAD

**Issue by 1ace** [McNopper/Vulkan#11]
![mcnopper-example-06](https://cloud.githubusercontent.com/assets/297576/15656679/b45801c4-26a1-11e6-844f-7ace635de176.png)

Mesa driver (`cee459d84de7533d0e0a74a37f7fc4c0f2b77bcf`, ie. head of `master` as of right now) on an Intel HD Graphics 530 (Skylake GT2)

I'd be happy to debug this if you give me a few hints 👍
(I don't know as much as I'd like about the "user" side of drivers… trying to learn more 😉)

**Comment by McNopper** [comment]
Okay, some questions from my side:
Is this bug new/did it work before?
Did you download the latest VKTS_Binaries? The scene file format did change a little bit.
Can you please delete the cache (contents of cache in VKTS_Binaries) and start again?

If the artifacts are still present, my suggestion to debug this:
- Enable/disable mipmapping (change flag in scene file)
- Debug "memoryImageCreate" function and check, where the textures are located (GPU or host).
  Also check, if GPU is used, how the images are staged and uploaded. If stageImage->copyImage(...) part is used, force to use stageBuffer->copyBufferToImage(...)

Please let me know the results.
