### ISSUE TITLE
Script for building and deploying examples

### ISSUE THREAD

**Issue by FslNopper** [McNopper/Vulkan#12]
Create a script, which builds all examples for the different platforms.

Also, create a script, which generates a ZIP file having the executables and assets in it.

**Comment by McNopper** [comment]
Done for Android.

**Comment by McNopper** [comment]
Also for MSVC and make files.

**Comment by McNopper** [comment]
Done since 
https://github.com/McNopper/Vulkan/commit/82586239f546e882bb7e844cf62bf3c346d076a9
