### ISSUE TITLE
I not found whear is shaders for VKTS_Example04 and VKTS_Example05

### ISSUE THREAD

**Issue by Ronniko** [McNopper/Vulkan#13]
Please show me text vertex and frag shaders for VKTS_Example04 and VKTS_Example05.

**Comment by McNopper** [comment]
Please have a look at the following document, where is noted what to do:
https://github.com/McNopper/Vulkan/blob/master/README.md
The shaders and assets are not commited to GitHub, as all files are already exteremly large.
