### ISSUE TITLE
linux build issues

### ISSUE THREAD

**Issue by CapsAdmin** [McNopper/Vulkan#14]
There are filename case issues In `vtkhs.hpp`. Like `#include <vkts/layer1/update/Parameter.hpp>` should be `#include <vkts/layer1/update/parameter.hpp>`

[After fixing this](https://gist.github.com/CapsAdmin/df7527a3a0ccbb278dba84cb1662b471) trying to build example 11 i get undefined reference for the function vkCreateXcbSurfaceKHR. I haven't looked much into this but shouldn't those functions be required with vk/GetInstance/Device/ProcAddress?

**Comment by McNopper** [comment]
I did do some refactoring and this commit should build without any problems:
https://github.com/McNopper/Vulkan/commit/165a3b800782f8d2c8c1e4b6d6e509094f0ca8a9

**Comment by McNopper** [comment]
Just tested under LInux as well. Works now.

For some reason, Eclipse did not do the git push to upstream. Deleted and the files and added them again.

Thanks a lot for reporting.
