### ISSUE TITLE
Split up scenegraph loader and graph into separte library

### ISSUE THREAD

**Issue by FslNopper** [McNopper/Vulkan#15]
NXP has its own demo framework and we would like to integrate the scenegraph functionality into it.
Actually, we would also like to use it for OpenGL and / or OpenGL ES.

So, what we ask for, do you see the possibility to move out the scenegraph functionality into its own library?

Beside us, probably other individuals and/or companies would like to see a separate library, that it does not have dependencies on the core library.

**Comment by McNopper** [comment]
Good point and makes sense.

Will implement this.

**Comment by McNopper** [comment]
Refactored code is currently in this branch:
https://github.com/McNopper/Vulkan/tree/master_1_0_33

VKTS packages do build; examples still need to be refactored.

Also, the packages and its dependencies still can change.

**Comment by McNopper** [comment]
Now available in master branch.
