### ISSUE TITLE
Not able to Render VKTS_Example08 on my Nvidia Quadro k6000 and AMD as well

### ISSUE THREAD

**Issue by pandurangkatkar** [McNopper/Vulkan#16]
I have Builded VKTS_Example for testing purpose but I am not able to render VKTS_Example08 as mention Vulkan examples based on VKTS: 

Geteing Below Info in CMD Window:
VKTS log [INFO] in 'fn_physical_device.cpp' at 102: Created physical device 'AMD Radeon (TM) R9 390 Series'
VKTS log [INFO] in 'fn_engine.cpp' at 160: Started.
VKTS log [INFO] in 'fn_engine.cpp' at 297: Thread 0 started.
VKTS log [INFO] in 'Example.cpp' at 850: Compute shader ongoing.
VKTS log [INFO] in 'Example.cpp' at 819: Compute shader done.
VKTS log [INFO] in 'Example.cpp' at 841: Saved image data as 'texture/mandelbrot.tga'
VKTS log [INFO] in 'UpdateThreadExecutor.cpp' at 76: UpdateThreadExecutor 0 update ended.
VKTS log [INFO] in 'fn_engine.cpp' at 305: Thread 0 stopped.
VKTS log [INFO] in 'fn_engine.cpp' at 359: Stopped.

System Info
OS : Win 7 and Win 10 Anniversary Update 
GPU : Nvidia Quadro k6000 and AMD Radeon (TM) R9 390

**Comment by McNopper** [comment]
Example 8 is not using any windowing system. It just uses core Vulkan by launching a compute shader, waits until the shader finishes, gathers the image data from device memory and stores it to disk. Regarding the log, everything worked fine. The output is stored in texture/mandelbrot.tga. You can deleete this TGA image and run example 8 again. Then, you can be sure it was generated by example 8 and your GPU.
