### ISSUE TITLE
What is keyboard Key to controller scene in Example06

### ISSUE THREAD

**Issue by pandurangkatkar** [McNopper/Vulkan#17]
What is keyborad Key to controller scene in  Example06,Example09,Example10 and Example12 as I don’t have Gamepad, I have tried with Arrow key and w, a, s & d keys but it’s not working in Win 7 and Win 10

**Comment by McNopper** [comment]
Change
vkts::inputControllerCreate(updateContext, visualContext, windowIndex, 0, camera);
to 
vkts::inputControllerCreate(updateContext, visualContext, windowIndex, -1, camera);
in any example.
Then it is WASD plus mouse control.

**Comment by McNopper** [comment]
Also, if you change
vkts::visualCreateWindow(display, VKTS_EXAMPLE_NAME, 1024, 768, VK_FALSE, VK_TRUE, VK_FALSE)
to
vkts::visualCreateWindow(display, VKTS_EXAMPLE_NAME, 1920, 1080, VK_TRUE, VK_FALSE, VK_TRUE)
you have "game like" behaviour.
