### ISSUE TITLE
Does those examples supports wayland?

### ISSUE THREAD

**Issue by DmitryHetman** [McNopper/Vulkan#18]

**Comment by McNopper** [comment]
Yes, under Linux tested (VeriSilicon GPU).
If you build with create_build_all_make.py:

python3 create_build_all_make.py VKTS_WAYLAND_VISUAL

If you use CMake, set VKTS_WSI to VKTS_WAYLAND_VISUAL

see https://github.com/McNopper/Vulkan/blob/master/VKTS_Documentation/Build.md
