### ISSUE TITLE
how do it

### ISSUE THREAD

**Issue by Steven201314** [McNopper/Vulkan#19]
When I use a non-rectangle ,like this ,
![effect](https://cloud.githubusercontent.com/assets/8087730/24494242/28fbd86e-1564-11e7-8660-eed3ac0ef734.png)
how could I do with the texture coordinate?

**Comment by McNopper** [comment]
![grafik](https://cloud.githubusercontent.com/assets/3677213/24497481/d78e60be-153b-11e7-9748-a3223350d976.png)

```
static const float vertices[4 * (4 + 2)] = {
-1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f,
1.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f,
-0.5f, -1.0f, 0.0f, 1.0f, 0.0f, 1.0f,
0.5f, -1.0f, 0.0f, 1.0f, 1.0f, 1.0f 
};
```
Think your GPU driver has a bug. Also, the changes are the NDC coordinates, not the texture ones.

**Comment by Steven201314** [comment]
You may try another image which likes this
![qq 20170330194157](https://cloud.githubusercontent.com/assets/8087730/24502572/f760416a-1580-11e7-836f-d40f7cadb066.png)

It's for 
![qq 20170329104449](https://cloud.githubusercontent.com/assets/8087730/24502590/0b85e88e-1581-11e7-850c-dc7c6c800864.jpg)

but the solution of it  has no goods for vk

**Comment by SaschaWillems** [comment]
Did you try the solution from my comment over at https://github.com/SaschaWillems/Vulkan/issues/310#issuecomment-290155891?

**Comment by McNopper** [comment]
![grafik](https://cloud.githubusercontent.com/assets/3677213/24504610/3810af76-1557-11e7-8c48-554be910fa57.png)
```
static const float vertices[4 * (4 + 2)] = {-1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f,
1.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f,
-1.0f, -2.0f, 0.0f, 2.0f, 0.0f, 1.0f,
1.0f, -2.0f, 0.0f, 2.0f, 1.0f, 1.0f 
};
```

**Comment by McNopper** [comment]
I still do not know what you want to achieve but probaly u need to read this:
http://www.geeks3d.com/20130514/opengl-interpolation-qualifiers-glsl-tutorial/

**Comment by Steven201314** [comment]
OH MY GOD,In our company ,the computers show all error,
As you said,the GPUs are all DOWN?!  Thanks you anyway!

**Comment by McNopper** [comment]
It is not the GPU driver. It is also not a Vulkan and/or GLSL issue. It is, how the GPU interpolates, and that is well defined. As you see in my second example, the "Correct" version does work. Just adapt the vertices,
If you want to have the "Affine" output, just use the first version.

**Comment by Steven201314** [comment]
In my project ,the vertex struct is 
struct MeshVertexts{
glm::vec3  pos;		
glm::vec3  normal;	
glm::vec3  color;	
glm::vec3  uv;	
}; 
I change your code like this 	
static const float vertices[4 * (4 + 2)] =
	{	-1.0f, 1.0f, 0.0f,  1.0f, 0.0f, 0.0f,
		1.0f, 1.0f, 0.0f,   1.0f, 1.0f, 0.0f,
		-0.5f, -2.0f, 0.0f, 2.0f, 0.0f, 1.0f,
		1.0f,  -2.0f, 0.0f, 2.0f, 1.0f, 1.0f
	};
the effect was happened 
![default](https://cloud.githubusercontent.com/assets/8087730/24507631/8536860e-1593-11e7-96fa-a2ec554c2260.jpg)
we should alert the  coordinates defined to deal with this effect.

**Comment by Steven201314** [comment]
I need to do “Projective interpolation of textures” compute to Fix this problem.5555

**Comment by McNopper** [comment]
Just use a projection matrix, which does the transformation of the vertices for you.
Do not try to do this by hand.

I thought, you want to understand the basics of the interpolation.

**Comment by Steven201314** [comment]
Ha,As you said  I needed to review the basics of 3D drawing. Thank you for your patience again
