### ISSUE TITLE
Better docs/asset loading

### ISSUE THREAD

**Issue by gigadude** [McNopper/Vulkan#2]
It would be nice if the [build docs](https://github.com/McNopper/Vulkan/blob/master/VKTS_Documentation/BUILD.md) clearly spelled out that you need to build in the VKTS dir first and download the binary assets.

Also hitting `F5` from VS should run the binaries correctly, either by [setting the working directory in cmake](http://stackoverflow.com/questions/23950887/does-cmake-offer-a-method-to-set-the-working-directory-for-a-given-build-system) or by using the app's binary path (OS specific) as the basis for searching for the shaders.

**Comment by McNopper** [comment]
I have updated the build docs to make it clear, that VKTS has to be build first and that the VKTS_Binaries folder has to be the working directory.

**Comment by McNopper** [comment]
VKTS is now trying to gather the base root directory. The improvement is available since here:
50aa0cc
