### ISSUE TITLE
Vulkan examples not working on Nvidia Linux Vulkan beta driver..

### ISSUE THREAD

**Issue by oscarbg** [McNopper/Vulkan#2]
I have fixed it by checking first xcb instead of xlib (the latter seems broken on Nvidia linux driver)
on both  _wsiGatherNeededInstanceExtensions and _wsiInitInstanceExtensions
The issue was also present on GLFW and already fixed:
See:https://github.com/glfw/glfw/issues/712

without the fix samples doesn't work with:
LOG [INFO]: Engine: Started.
LOG [INFO]: Engine: Thread 0 started.
LOG [ERROR]: Example: Could not initialize instance extensions.
LOG [ERROR]: UpdateThreadExecutor 0: Run failed! Update thread Initialize failed.
LOG [INFO]: Engine: Thread 0 stopped.
LOG [INFO]: Engine: Stopped.

**Comment by McNopper** [comment]
XCB is now preferred and should fix the problem:
https://github.com/McNopper/Vulkan/commit/5a27811cffc7cff1351f0d8bc87c8327b262f751

Which Linux derivative are you using?

**Comment by oscarbg** [comment]
Ubuntu 15.10..
don't know if using Padoka PPA has update some X components..
also kernel 4.5rc3 from PPA.

**Comment by McNopper** [comment]
I am testing the Linux version with the LunarG Intel driver. On a quick try, my Ubuntu 15.10 did not like the NVIDIA Vulkan driver. After rebooting, it always crashes back to login.

**Comment by oscarbg** [comment]
I installed downloading deb from Vulkan ppa..
are you testing with LunarG Intel driver or 01.org anvil mesa driver as
tried building lunarg driver from Vulkantools ICD folder but requires login
to Khronos CVS to fetch some files so can't get..

2016-02-19 11:17 GMT+01:00 Norbert Nopper <notifications@github.com>:

**Comment by McNopper** [comment]
I have a dedicated Haswell Linux machine. So yes, I am testing with the LunarG Intel driver, as the offical driver from Intel is not supporting Haswell at the moment. But I know they are working on it.

**Comment by oscarbg** [comment]
You would made me happy if you can upload report using VulkanCapsViewer (
http://vulkan.gpuinfo.org/download.php)
I uploaded a Skylake GPU (http://vulkan.gpuinfo.org/displayreport.php?id=53)
using ANvil mesa driver so we could compare to LunarG drivers in terms of
caps..
PS:do you tkink reports like
http://vulkan.gpuinfo.org/displayreport.php?id=70 that report Haswell are
using LunarG driver, then?


2016-02-20 0:31 GMT+01:00 Norbert Nopper <notifications@github.com>:
