### ISSUE TITLE
Programmatic scene setup example request

### ISSUE THREAD

**Issue by skesgin** [McNopper/Vulkan#20]
Hello,

First of all, thank you for the project. As a hobbyist, I find it to be a great resource for learning both about Vulkan and also creating a graphics engine.

However, I must say that there is a great need for an example which shows how to setup a scene entirely programmatically, without any external data files. Creating and setting up the lights, the camera, input controls and especially the mesh data.

Do you have any plans in this regards?
Thanks

**Comment by McNopper** [comment]
Not at this point of time, as it is all "there".
You just need to debug into the VKTS packages - then you get all the details.
