### ISSUE TITLE
It is not correct to decide the output by comparing primary output and connected output

### ISSUE THREAD

**Issue by davidmaoamd** [McNopper/Vulkan#4]
Regarding to example01, the test cannot start correctly because it cannot find the valid display after enumerating.
The reason behind that is the X_RRGetOutputPrimary returns 0 for primary_output, but the connected output getting from XRRGetOutputInfo is valid. 
The primary output and connected output are different concept. 
It is not always true to assume the driver will report the primary output, thus it is not a proper way to rely on this to determine the output for current screen. 
We, (AMD), will try to setup the primary output in our driver but at the same time, I would like the application to change the behavior as well. 
Thanks.

**Comment by McNopper** [comment]
I will dig into this. Can you please give me more information on your setup:
- Monitor count.
- Linux derivate and version
- AMD graphics card
- Driver version

**Comment by davidmaoamd** [comment]
Thanks for the quick response.
Monitor Count : one monitor only. 
OS: Ubuntu16.04
Graphic Card: Bonaire XTX
Driver Version : 16.20.

**Comment by McNopper** [comment]
Where can I download this driver for Ubuntu 16.04?
I do have access to your community website as well.

**Comment by davidmaoamd** [comment]
I just realize we has not publish the latest driver yet. 
Please wait couple of days, and I will send you a link if driver is released on schedule. 
BTW: Which vendor's Graphic card are you using to develop the demo, NVidia?

**Comment by McNopper** [comment]
Yes, but I also do have an AMD 7970 card in my wifes computer :-)

So, I tested the Linux code only under NVIDIA and Intel (LunarG Haswell driver) so far.
But for Windows, I tested the code also for AMD.

**Comment by McNopper** [comment]
I just tested VKTS_Test_Input (which does not need a Vulkan driver) under Ubuntu 16.04 and an AMD GPU. Using the included Gallium driver, the displays could be enumerated.

I will wait, until I do have access to the driver.

**Comment by McNopper** [comment]
I have made the default display detection under Linux more relaxed. Please try this version: 86667d7

Please reopen, if this does not work.
