### ISSUE TITLE
VKTS_Example04: App attempts to transfer stage image into invalid image layout

### ISSUE THREAD

**Issue by kbiElude** [McNopper/Vulkan#4]
In fn_texture.cpp::textureCreate(), we have the following code block:

![image](https://cloud.githubusercontent.com/assets/9154207/13279474/7628427a-dad8-11e5-9f62-6825b980e1fc.png)

Consider this call stack:

![image](https://cloud.githubusercontent.com/assets/9154207/13279504/af2a7c14-dad8-11e5-8132-8fa13bb20762.png)

In this scenario, the application attempts to initialize an image with VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT image usages. In order to upload data to the texture, it needs to use a stage image. The stage image is created correctly, but the app then attempts to transfer it to SHADER_READ_ONLY_OPTIMAL layout, which is invalid and causes a crash in our driver. This is likely due to invalid newLayout argument, passed to texturePrepare() call, as per picture below:

![image](https://cloud.githubusercontent.com/assets/9154207/13279573/31528722-dad9-11e5-9d6f-1b1e61687292.png)

Please consider using Khronos validation layers in your applications. They can be helpful in capturing omissions like the one I'm describing.

**Comment by McNopper** [comment]
Normally, I have enabled the layers by default. Maybe I was working with an old version. I will investigate this.

**Comment by kbiElude** [comment]
I'm from the AMD driver team, so there's only one driver I could be using :-)

**Comment by McNopper** [comment]
Okay, tested on NVIDIA and Intel. Will now retest for AMD.

**Comment by McNopper** [comment]
Removed all layer warnings/errors in AMD path:
Example 1-7 working on NVIDIA
Example 1-6 working on Intel Haswell (7 uses geometry and teessellation shaders - okay)
Example 1-4 working on AMD (5-7 artifacts or no content, no crashes - not okay)

**Comment by McNopper** [comment]
I think all code paths are now tested and all errors and warnings are removed.

**Comment by kbiElude** [comment]
Yeah, I'm aware of the glitches. Will be giving these a closer look today or tomorrow.

**Comment by McNopper** [comment]
I have fixed/improved some issues and uploaded the changes. Example 1-5 is now fine on AMD, Intel and Nvidia. With AMD driver 02/26, example 7 did also improve, as terrain is "more" vissible.

**Comment by kbiElude** [comment]
Will definitely be having a look tomorrow. Thanks for all the support!

**Comment by McNopper** [comment]
Thanks a lot. I will continue on example 7 and also look at my other code. Hope, that my examples sooner or later run on Android, Linux and Windows with any GPU!
