### ISSUE TITLE
Assets misaligned in Example09

### ISSUE THREAD

**Issue by TheBuzzSaw** [McNopper/Vulkan#49]
Am I the only one seeing this?

![misalign](https://user-images.githubusercontent.com/290188/29855573-0e81d90c-8d0a-11e7-8518-ca1b5f22a628.png)

I'm running the sample in Arch Linux on a GTX 970 running the proprietary driver.

**Comment by TheBuzzSaw** [comment]
Example12 looks mostly fine, but the spinning blades wobble a crazy amount. Methinks there is a slight mesh/animation issue there too. I'd need to capture a video to really show the problem there.

**Comment by McNopper** [comment]
We are currently working hard on re-releasing this library as an engine. What you experience is a known issue, when using glTF and VKTS files in this old library (switching to only quaternion rotations). 

It's working fine in our local repo :-) Please wait, until we open source it again. So I close this issue for now.

![grafik](https://user-images.githubusercontent.com/3677213/29855929-cdd760a2-8d4f-11e7-813a-440a7328952d.png)

![grafik](https://user-images.githubusercontent.com/3677213/29855991-2c2acdd8-8d50-11e7-8e83-d4f150fdc7a9.png)

**Comment by TheBuzzSaw** [comment]
Ah. Good to know.
