### ISSUE TITLE
Uniform Buffers Multiple Upload

### ISSUE THREAD

**Issue by MichaelWei1990** [McNopper/Vulkan#50]
I am wondering if there are particular reasons why the upload function uniform buffers, one for the view and projection matrix (in the example.cpp file) and the other one for the model and normal matrix (in node.cpp), are being called twice, each time for copying the memory of the values in a matrix. If it is possible to create a structure containing the two matrices data and then call the upload function only once with a providing size of the structure. 
If yes, what changes shall I make to achieve the goal, especially for the dynamic offset? The code seems unable to do so because of the dynamic offset.

**Comment by McNopper** [comment]
There are several convenient functions to upload e.g. vec3, vec4, mat3 and mat4. Of course, it is also possible to upload data at any size.

**Comment by MichaelWei1990** [comment]
Yes, there are several functions to upload glm parameters, which are convenient. However, I tried uploading the dynamic uniform buffers (view projection uniform buffer and transform uniform buffer) with two matrices by only once, however, it only works for view projection uniform buffer because its binding is 0.  I guess I must have understood the dynamic offset improperly, so it would be very nice if you could provide more details about how it works.
