### ISSUE TITLE
Image::copyImage() uses incorrect access masks

### ISSUE THREAD

**Issue by kbiElude** [McNopper/Vulkan#6]
Consider the following code block:

![image](https://cloud.githubusercontent.com/assets/9154207/13315252/ef5aac56-dba9-11e5-9a3f-1e5b462bad7f.png)

The access masks are incorrectly defined. This is very likely leading to broken texture data which leads to visual glitches we're seeing in VKTS_Example05 and beyond.

**Comment by McNopper** [comment]
Hmmm, these values should not be there. Think I have to revisit some code parts and check, if my search and replace steps did result in valid code. I am currently AFK and will check this ASAP. Thanks a lot for finding this.

**Comment by McNopper** [comment]
Removed the values but main causing issue on my side was missing layout qualifiers in the shaders.
This is fixed and example 5 also runs fine on AMD.
https://github.com/McNopper/Vulkan/commit/0e4b76d438e1d12bf88431604f0e3b98df7e79d2
