### ISSUE TITLE
You are not allowed to transition swapchain images without first acquiring them.

### ISSUE THREAD

**Issue by ratchetfreak** [McNopper/Vulkan#7]
https://github.com/McNopper/Vulkan/blob/master/VKTS_Example01/src/Example.cpp#L580

Here you transition the images from the swapchain from UNDEFINED to PRESENT without first having acquired them.

https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#_wsi_swapchain

>  Use of a presentable image must occur only after the image is returned by vkAcquireNextImageKHR, and before it is presented by vkQueuePresentKHR. **This includes transitioning the image layout and rendering commands.**

You can instead always transition from UNDEFINED instead of PRESENT after acquiring them. This is well defined and implies that you don't want to keep the data in the image.

**Comment by McNopper** [comment]
Correct and fixed in eedd20c
