### ISSUE TITLE
VK_Example07: texture() must not be used in geometry shader stage

### ISSUE THREAD

**Issue by kbiElude** [McNopper/Vulkan#7]
phong_displace.geom issues a texture() instruction. As per GL SL specification, implicit mip texel fetches are only allowed in fragment shaders.

Replacing texture() invocation with textureLod(), with LOD arg set to 0.0 fixes the application:

**Comment by McNopper** [comment]
You are right. Just wondering why glslangValidator is not repoerting anything.
Fixed here:
https://github.com/McNopper/Vulkan/commit/730fe128beae9b830e730d833ed1b77585060777
