### ISSUE TITLE
Release builds created by VS15 crash at start-up

### ISSUE THREAD

**Issue by kbiElude** [McNopper/Vulkan#8]
A crash occurs if a Release build of any of the example applications is launched:

![image](https://cloud.githubusercontent.com/assets/9154207/13461185/52c3d648-e080-11e5-9854-8071140eb947.png)

This happens before a Vulkan instance is even created, so I suspect we might be dealing with either a compiler, or an app-side bug here.

**Comment by McNopper** [comment]
Wow, found it:
Under Windows, during initialisation of the keyboard lookup table, I do write out of bounds.
This causes the crash in Release. This also caused a crash when exiting the examples with a MinGW build.

This was an important and "evil" bug! Thank you very much!

Fixed here:
https://github.com/McNopper/Vulkan/commit/61175ed0af0dcf13116ce81d271d1c81c4603999
