### ISSUE TITLE
How draw many objects without instancing ?

### ISSUE THREAD

**Issue by Ronniko** [McNopper/Vulkan#9]
I try create one big uniform buffer for 15 objects.
For one object three matrices.
Then do uniformDataVS.descriptor.offset += 64*3
vkUpdateDescriptorSets and in CmdBuffer set descriptorSet1, then descriptorSet2, then descriptorSet3

I create 15 CmdBuffers and set different descriptorSets then vkQueueSubmit cmdbuffers list(15)
But all objects draws in one place.
But i create different matrices for objects.
Can we expect from you an example ?
I create maximum cmdbuffers 880 ! Then Vulkan get me error.
Radeon HD7950 3Gb videoram

**Comment by Ronniko** [comment]
Its cool for frustum culling.

**Comment by McNopper** [comment]
I will add frustum culling to example 7: When rendering the 64 patches of the terrain, non visible patches will not be recored in the multi-threaded application.
If it is the same object, I suggest to use instancing. Also, you can multiply the objects in the geometry shader but this is probably slow.
Sorry, I cannot help you on this.
