### ISSUE TITLE
No terrain visible in example 07 on Android

### ISSUE THREAD

**Issue by SaschaWillems** [McNopper/Vulkan#9]
On my Shield TV the terrain in example 07 is not visible, it only shows an untextured plane instead with patches changing visibility when moving the camera :

![vkts_example07_20160521_103846](https://cloud.githubusercontent.com/assets/10283127/15447426/5c56da7e-1f42-11e6-8435-e820136d7bb0.png)

ADB log output shows no errors and also logs all resources as loaded (texture and terrain).

**Comment by McNopper** [comment]
Works fine on NVIDIA Shield K1:

![device-2016-05-21-122734](https://cloud.githubusercontent.com/assets/3677213/15447846/9c4d272a-1f4f-11e6-8b45-c266d1db0eef.png)

**Comment by McNopper** [comment]
Assume, this is a driver bug.

In example 7, I lately removed a validation layer error. Moved the secondary command buffer execution in its own subpass. Works fine on NVIDIA desktop and Shield K1 and also on AMD desktop GPU.
Will not fix it, as I also do have a Google Nexus Player, where I do have artifacts in other examples as well.
Will revisit the examples as soon as Android N is final.
